In [2]:
import sys
import pandas as pd
import numpy as np
import tensorflow as tf
pd.__version__
# from google.colab import drive

'1.0.4'

In [3]:
data = pd.read_csv("train.csv", encoding='big5')
data

日期  測站          測項     0     1     2     3     4     5     6  \
0       2014/1/1  豐原    AMB_TEMP    14    14    14    13    12    12    12   
1       2014/1/1  豐原         CH4   1.8   1.8   1.8   1.8   1.8   1.8   1.8   
2       2014/1/1  豐原          CO  0.51  0.41  0.39  0.37  0.35   0.3  0.37   
3       2014/1/1  豐原        NMHC   0.2  0.15  0.13  0.12  0.11  0.06   0.1   
4       2014/1/1  豐原          NO   0.9   0.6   0.5   1.7   1.8   1.5   1.9   
...          ...  ..         ...   ...   ...   ...   ...   ...   ...   ...   
4315  2014/12/20  豐原         THC   1.8   1.8   1.8   1.8   1.8   1.7   1.7   
4316  2014/12/20  豐原       WD_HR    46    13    61    44    55    68    66   
4317  2014/12/20  豐原  WIND_DIREC    36    55    72   327    74    52    59   
4318  2014/12/20  豐原  WIND_SPEED   1.9   2.4   1.9   2.8   2.3   1.9   2.1   
4319  2014/12/20  豐原       WS_HR   0.7   0.8   1.8     1   1.9   1.7   2.1   

      ...    14    15    16    17    18    19    20    21    22    23  
0     ...    22    22    21    19    17    16    15    15    15    15  
1     ...   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8  
2     ...  0.37  0.37  0.47  0.69  0.56  0.45  0.38  0.35  0.36  0.32  
3     ...   0.1  0.13  0.14  0.23  0.18  0.12   0.1  0.09   0.1  0.08  
4     ...   2.5   2.2   2.5   2.3   2.1   1.9   1.5   1.6   1.8   1.5  
...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  
4315  ...   1.8   1.8     2   2.1     2   1.9   1.9   1.9     2     2  
4316  ...    59   308   327    21   100   109   108   114   108   109  
4317  ...    18   311    52    54   121    97   107   118   100   105  
4318  ...   2.3   2.6   1.3     1   1.5     1   1.7   1.5     2     2  
4319  ...   1.3   1.7   0.7   0.4   1.1   1.4   1.3   1.6   1.8     2  

[4320 rows x 27 columns]

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4320 entries, 0 to 4319
Data columns (total 27 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   日期      4320 non-null   object
 1   測站      4320 non-null   object
 2   測項      4320 non-null   object
 3   0       4320 non-null   object
 4   1       4320 non-null   object
 5   2       4320 non-null   object
 6   3       4320 non-null   object
 7   4       4320 non-null   object
 8   5       4320 non-null   object
 9   6       4320 non-null   object
 10  7       4320 non-null   object
 11  8       4320 non-null   object
 12  9       4320 non-null   object
 13  10      4320 non-null   object
 14  11      4320 non-null   object
 15  12      4320 non-null   object
 16  13      4320 non-null   object
 17  14      4320 non-null   object
 18  15      4320 non-null   object
 19  16      4320 non-null   object
 20  17      4320 non-null   object
 21  18      4320 non-null   object
 22  19      4320 non-null   

In [4]:
data_jan = data(data['日期'] == '2014/1/1': data['日期'] == '2014/1/20',)

测站:
 ['豐原']


In [5]:
data[data['日期'] == '2014/1/3']


日期  測站          測項     0     1     2     3     4     5     6  ...  \
36  2014/1/3  豐原    AMB_TEMP    18    18    18    18    18    18    18  ...   
37  2014/1/3  豐原         CH4   1.8   1.8   1.8   1.8   1.8   1.7   1.7  ...   
38  2014/1/3  豐原          CO  0.32  0.35  0.37  0.31  0.29  0.27   0.3  ...   
39  2014/1/3  豐原        NMHC  0.12  0.18  0.15  0.13  0.16  0.07  0.07  ...   
40  2014/1/3  豐原          NO   1.2   1.3   1.2   0.9   0.9   0.8   1.1  ...   
41  2014/1/3  豐原         NO2     8   9.7    10   7.2   7.4   6.2   7.7  ...   
42  2014/1/3  豐原         NOx   9.2    11    11   8.1   8.3     7   8.8  ...   
43  2014/1/3  豐原          O3    34    28    30    33    30    34    33  ...   
44  2014/1/3  豐原        PM10    38    27    31    33    30    19    12  ...   
45  2014/1/3  豐原       PM2.5    19    25    27    20    16    14    15  ...   
46  2014/1/3  豐原    RAINFALL    NR    NR    NR    NR    NR    NR   1.2  ...   
47  2014/1/3  豐原          RH    72    73    73    76    76    76    84  ...   
48  2014/1/3  豐原         SO2   1.7   2.8   2.7   2.8   2.3     2   1.6  ...   
49  2014/1/3  豐原         THC   1.9     2   1.9   1.9   1.9   1.8   1.8  ...   
50  2014/1/3  豐原       WD_HR   117   106    91   115    93   115   101  ...   
51  2014/1/3  豐原  WIND_DIREC   111    71   122   145   116   110    77  ...   
52  2014/1/3  豐原  WIND_SPEED   1.5   1.6   1.2   1.6   1.3   2.8   1.4  ...   
53  2014/1/3  豐原       WS_HR   1.7   1.2   1.2   1.2   1.2     2   1.3  ...   

      14    15    16    17    18   19    20    21    22    23  
36    24    22    22    21    20   20    20    20    20    19  
37   1.8   1.8   1.8   1.8   1.8  1.8   1.8   1.8   1.8   1.8  
38  0.31  0.34  0.42  0.53  0.55  0.6  0.49  0.28  0.35  0.37  
39  0.18  0.19  0.22  0.32  0.24  0.3  0.23  0.06   0.2  0.22  
40   2.2   2.3   3.1     2   1.3  2.7   1.6   1.1   1.1   1.4  
41    11    15    26    22    25   29    19   6.1   9.6    11  
42    13    17    29    24    26   32    20   7.2    11    12  
43    50    45    30    26    19   10    20    37    29    22  
44    41    56    68    73    72   70    61    53    50    52  
45    32    36    34    45    40   41    23    29    23    37  
46    NR    NR    NR    NR    NR   NR    NR    NR    NR    NR  
47    58    62    65    70    71   73    72    66    69    74  
48   3.4   4.3     8   3.8   3.8  3.8   3.3   2.2   2.3   2.2  
49   1.9   1.9     2   2.1     2  2.1     2   1.8     2     2  
50   311   314   309    42    54   48    61    95   6.5    45  
51   310   319   314    48    57   46    61    82    63    31  
52     3   2.5   1.5   1.6   1.4  1.2   1.8   1.4   1.5   1.4  
53   2.1     2   1.4   0.6   1.3  0.7   1.2   2.5   0.4   0.5  

[18 rows x 27 columns]

In [6]:
data = data.iloc[:, 3:]
data[data == 'NR'] = 0
# data[data['日期'] == '2014/1/3']

In [7]:
raw_data = data.to_numpy()
raw_data

array([['14', '14', '14', ..., '15', '15', '15'],
       ['1.8', '1.8', '1.8', ..., '1.8', '1.8', '1.8'],
       ['0.51', '0.41', '0.39', ..., '0.35', '0.36', '0.32'],
       ...,
       ['36', '55', '72', ..., '118', '100', '105'],
       ['1.9', '2.4', '1.9', ..., '1.5', '2', '2'],
       ['0.7', '0.8', '1.8', ..., '1.6', '1.8', '2']], dtype=object)

In [8]:
month_data = {}
for month in range(12):
    sample = np.empty([18, 480])
    for day in range(20):
        sample[:, day * 24 : (day + 1) * 24] = raw_data[18 * (20 * month + day) : 18 * (20 * month + day + 1), :]
    month_data[month] = sample
month_data

{0: array([[14.  , 14.  , 14.  , ..., 14.  , 13.  , 13.  ],
        [ 1.8 ,  1.8 ,  1.8 , ...,  1.8 ,  1.8 ,  1.8 ],
        [ 0.51,  0.41,  0.39, ...,  0.34,  0.41,  0.43],
        ...,
        [35.  , 79.  ,  2.4 , ..., 48.  , 63.  , 53.  ],
        [ 1.4 ,  1.8 ,  1.  , ...,  1.1 ,  1.9 ,  1.9 ],
        [ 0.5 ,  0.9 ,  0.6 , ...,  1.2 ,  1.2 ,  1.3 ]]),
 1: array([[ 15.  ,  14.  ,  14.  , ...,   8.4 ,   8.  ,   7.6 ],
        [  1.8 ,   1.8 ,   1.7 , ...,   1.7 ,   1.7 ,   1.7 ],
        [  0.27,   0.26,   0.25, ...,   0.36,   0.35,   0.32],
        ...,
        [113.  , 109.  , 104.  , ...,  72.  ,  65.  ,  69.  ],
        [  2.3 ,   2.2 ,   2.6 , ...,   1.9 ,   2.9 ,   1.5 ],
        [  2.5 ,   2.2 ,   2.2 , ...,   0.9 ,   1.6 ,   1.1 ]]),
 2: array([[ 18.  ,  18.  ,  18.  , ...,  14.  ,  13.  ,  13.  ],
        [  1.8 ,   1.8 ,   1.8 , ...,   1.8 ,   1.8 ,   1.8 ],
        [  0.39,   0.36,   0.4 , ...,   0.42,   0.47,   0.49],
        ...,
        [103.  , 128.  , 115.  , ...,  

In [9]:
x = np.empty([12 * 471, 18 * 9], dtype = float)
y = np.empty([12 * 471, 1], dtype = float)
for month in range(12):
    for day in range(20):
        for hour in range(24):
            if day == 19 and hour > 14:
                continue
            x[month * 471 + day * 24 + hour, :] = month_data[month][:,day * 24 + hour : day * 24 + hour + 9].reshape(1, -1) #vector dim:18*9 (9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9)
            y[month * 471 + day * 24 + hour, 0] = month_data[month][9, day * 24 + hour + 9] #value
print(x)
print(y)

[[14.  14.  14.  ...  2.   2.   0.5]
 [14.  14.  13.  ...  2.   0.5  0.3]
 [14.  13.  12.  ...  0.5  0.3  0.8]
 ...
 [17.  18.  19.  ...  1.1  1.4  1.3]
 [18.  19.  18.  ...  1.4  1.3  1.6]
 [19.  18.  17.  ...  1.3  1.6  1.8]]
[[30.]
 [41.]
 [44.]
 ...
 [17.]
 [24.]
 [29.]]


In [10]:
mean_x = np.mean(x, axis = 0) #18 * 9 
std_x = np.std(x, axis = 0) #18 * 9 
for i in range(len(x)): #12 * 471
    for j in range(len(x[0])): #18 * 9 
        if std_x[j] != 0:
            x[i][j] = (x[i][j] - mean_x[j]) / std_x[j]
x

array([[-1.35825331, -1.35883937, -1.359222  , ...,  0.26650729,
         0.2656797 , -1.14082131],
       [-1.35825331, -1.35883937, -1.51819928, ...,  0.26650729,
        -1.13963133, -1.32832904],
       [-1.35825331, -1.51789368, -1.67717656, ..., -1.13923451,
        -1.32700613, -0.85955971],
       ...,
       [-0.88092053, -0.72262212, -0.56433559, ..., -0.57693779,
        -0.29644471, -0.39079039],
       [-0.7218096 , -0.56356781, -0.72331287, ..., -0.29578943,
        -0.39013211, -0.1095288 ],
       [-0.56269867, -0.72262212, -0.88229015, ..., -0.38950555,
        -0.10906991,  0.07797893]])